default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: SecondBlog_database_development

 
test:
  <<: *default
  database: SecondBlog_database_test

production:
  <<: *default
  database: SecondBlog_database_production
  username: postgres
  password: <%= ENV["BLOG_DATABASE_PASSWORD"] %>
